version: "2"
services: 
  jetty9_8:
    image: jetty:9-jre8
    ports: 
      - 8080:8080
    volumes: 
      - ./data/webapps:/usr/local/tomcat/webapps
      - ./data/logs:/usr/local/tomcat/logs
    restart: always
    privileged: true
    