version: "3"
services: 
  mysql80_3307:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - /root/mysql/80/:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - 3307:3306
    restart: always