version: "2"
services: 
  percona:
    image: percona:8.0
    ports: 
      - 3307:3306
    volumes: 
      - ./data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
    restart: always
    privileged: true

