version: "3"
services: 
  elasticsearch:
    image: elasticsearch:6.8.7
    ports: 
      - 9200:9200
      - 9300:9300
    volumes: 
      - /root/elasticsearch/687/data:/usr/share/elasticsearch/data
    environment: 
      - discovery.type=single-node
