version: "2.2"
services: 
  elasticsearch76:
    mem_limit: 2g
    image: elasticsearch:7.6.1
    ports: 
      - 9200:9200
      - 9300:9300
    volumes: 
      - ./data:/usr/share/elasticsearch/data
    environment: 
      - discovery.type:single-node
    privileged: true
