version: "2.2"
services: 
  elasticsearch76:
    mem_limit: 2048m
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 9200:9200
      - 9300:9300
    volumes: 
      - ./data:/usr/share/elasticsearch/data
      - ./logs:/usr/share/elasticsearch/logs
    environment: 
      - discovery.type:single-node
    privileged: true
