version: "3"
services: 
  elasticsearch76:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 9200:9200
      - 9300:9300
    volumes: 
      - /root/elasticsearch/76/data:/usr/share/elasticsearch/data
    environment: 
      - discovery.type:single-node
    privileged: true
