version: "3"
services: 
  elasticsearch76:
    image: elasticsearch:7.6.1
    ports: 
      - 9200:9200
      - 9300:9300
    volumes: 
      - /root/elasticsearch/761/data:/usr/share/elasticsearch/data
    environment: 
      - discovery.type:single-node
