version: "3"
services: 
  rabbitmq38:
    image: rabbitmq:3.8
    ports: 
      - 15672:15672
      - 5672:5672
    volumes: 
      - /root/rabbit/data:/var/lib/rabbitmq/mnesia/
    environment: 
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    restart: always