version: "2"
services: 
  spring_boot:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    privileged: true
    ports: 
      - 8106:8081
    depends_on: 
      - mysql80
    links: 
      - mysql80:mysql
  mysql80:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - ./data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_01
    restart: always
    privileged: true