version: "2"
services: 
  spring_boot:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    privileged: true
    ports: 
      - 8101:8081
    networks: 
      - spring_boot_app