version: "3"
services: 
  nginx80:
    image: nginx
    ports: 
      - 80:80
    restart: always
    volumes: 
      - /root/nginx/conf:/etc/nginx/conf.d:rw
      - /root/nginx/log:/var/log/nginx:rw
      - /root/nginx/html:/usr/share/nginx/html
    
