version: "3"
services: 
  mysql80_3306:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - /root/mysql/57/:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - 3306:3306