version: "3"
services: 
  mysql80_3307:
    image: mariadb:10.5.1
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - /root/mariadb1051/:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - 3308:3306