version: "3"
services: 
  tomcat90_11:
    image: tomcat:9-jdk11
    ports: 
      - 8080:8080
    volumes: 
      - ./webapps:/usr/local/tomcat/webapps
      - ./logs:/usr/local/tomcat/logs
    restart: always
    privileged: true

