version: '3.1'
services:
  mongo3:
    image: mongo:3-xenial
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports: 
      - 27017:27017
    volumes: 
      - /root/mongo/3/data:/data/db
    restart: always